travis:
  secure:
    BINSTAR_TOKEN: PZHT7/O1MlylELgTTzO08XKh9+rgh4O0E0AGqqIyzl3pL/c4kxremvaCYG+zHtpWW9FHKGN8NciBEChYzN7MWrrqecVeCKMaltNOAsWj2NnmqiJZTDGB74naBDn3gmmcIHH3kk0pzbwEztqpc9jxI/C4hREqfJmOaGghiaEVPIb+8Sxr+97z07IFbTkSaczOcqYlT5tncQBjmWLZc3LpYpcMsA2XFdl0d+QsTcZMmP/+VWR6yASwcsU66fTQPYAzTX4WM5/Dbt5qxoKkAMrv9uPygstbcaTRGgQSrKr9zOJ/2d10+UPuxwQOOvWtBe0Q5KkwV3n7WcyRttv5s/OUMFSPKcXohBLIsJp77NGehYOTEHVUSWREaG5V+jrhZtYtEE0SjvmC4CC2s3ar5/T23AlKlNhYcnFwRHhnayd+y90L3ZjoMV2PAcXNphAg8rxExhXP7YN/4znMwwohBCldifXjd1HZEc0pOyPvuPDCjTRj1LCc6Vb0OH6DlSll4KxtEenPNxOHajpnUQfTcWM9IIBOkOH95fOFfhF2j2hFLimcfiMgYTnc81opY7010ZFfbO8aLeRv0PvUxf8MHkLAF2fExJkfJj8h0zUk7UY9fKXcq4gO3IjCJehIo+rz+DRa/NE5PNH1Gdsr0hr5s0VwZdKrlm1NAkB96ia/t5CWaag=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
